package interfaz;

import BD.GestionBD;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import modelos.Departamento;
import modelos.Departamentos;
import modelos.Empleado;
import modelos.Empleados;
import modelos.Ficha;
import modelos.Fichas;

/**
 *
 * @author damm
 */
public class EmpresaGUI extends javax.swing.JFrame {

    // Objeto para conectarno a la BD
    GestionBD conexion;

    // Listados de Empleados, Departamentos y Fichas
    Departamentos listaDepartamentos;
    Empleados listaEmpleados;
    Fichas listaFichas;

    // Modelo JList de Departamentos, Empleados y Fichas
    DefaultListModel modeloJlistDptos;
    DefaultListModel modeloJlistEmpleados;
    DefaultListModel modeloJlistFichar;
    
    // Modelo ComboBox para Empleados
    DefaultComboBoxModel modeloComboDepartamentosEmp;    

    /**
     * Creates new form Interfaz
     */
    public EmpresaGUI() {
        // Inicializamos los datos de Modelos
        modeloJlistDptos = new DefaultListModel();
        modeloJlistEmpleados = new DefaultListModel();
        modeloJlistFichar = new DefaultListModel();
        modeloComboDepartamentosEmp = new DefaultComboBoxModel();

        // Inicializamos listado de Departamentos, Empleados y Fichas
        listaDepartamentos = new Departamentos();
        listaEmpleados = new Empleados();
        listaFichas = new Fichas();
        

        // Creamos la conexión a la BD
        conexion = new GestionBD("localhost", "javier",
                "javier", "empresa_v2"
        );

        // Cargamos los departamentos y los empleados
        listaDepartamentos = conexion.listarDepartamentos();
        listaEmpleados = conexion.listarEmpleados();
        
        cargarDepartamentos();
        cargarEmpleados();
        cargarFichas();
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TabEmpleados = new javax.swing.JPanel();
        PanelListadoEmpleados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListEmpleados = new javax.swing.JList<>();
        PanelDetalleEmpleados = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JTexFieldEmpleadoID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTexFieldEmpleadoNombre = new javax.swing.JTextField();
        BtGuardarEmpleado = new javax.swing.JButton();
        BtNuevoEmpleado = new javax.swing.JButton();
        BtBorrarEmpleado = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JTexFieldEmpleadoApellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JTexFieldEmpleadoEmail = new javax.swing.JTextField();
        CbEmpleadosDpto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        spinnerEmpleadoSalario = new javax.swing.JSpinner();
        TabDepartamentos = new javax.swing.JPanel();
        PanelListadoDepartamentos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDpto = new javax.swing.JList<>();
        PanelDetalleDepartamento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTexFieldDptoID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTexFieldDptoNombre = new javax.swing.JTextField();
        BtGuardarDpto = new javax.swing.JButton();
        BtNuevoDpto = new javax.swing.JButton();
        BtBorrarDpto = new javax.swing.JButton();
        TabFichas = new javax.swing.JPanel();
        PanelListadoFichas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListFichas = new javax.swing.JList<>();
        PanelDetalleFicha = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldFichaID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldFichaNombreEmpleado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButtonGuardarFicha = new javax.swing.JButton();
        jButtonNuevaFicha = new javax.swing.JButton();
        jButtonBorrarFicha = new javax.swing.JButton();
        jTextFieldFichaTipoFichado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelListadoEmpleados.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado:"));

        jListEmpleados.setModel(modeloJlistEmpleados);
        jListEmpleados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListEmpleadosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListEmpleados);

        javax.swing.GroupLayout PanelListadoEmpleadosLayout = new javax.swing.GroupLayout(PanelListadoEmpleados);
        PanelListadoEmpleados.setLayout(PanelListadoEmpleadosLayout);
        PanelListadoEmpleadosLayout.setHorizontalGroup(
            PanelListadoEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelListadoEmpleadosLayout.setVerticalGroup(
            PanelListadoEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelDetalleEmpleados.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle:"));

        jLabel3.setText("ID:");

        JTexFieldEmpleadoID.setEditable(false);
        JTexFieldEmpleadoID.setEnabled(false);
        JTexFieldEmpleadoID.setPreferredSize(new java.awt.Dimension(70, 23));

        jLabel4.setText("Nombre:");

        BtGuardarEmpleado.setText("GUARDAR");
        BtGuardarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardarEmpleadoActionPerformed(evt);
            }
        });

        BtNuevoEmpleado.setText("NUEVO");
        BtNuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNuevoEmpleadoActionPerformed(evt);
            }
        });

        BtBorrarEmpleado.setText("BORRAR");
        BtBorrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBorrarEmpleadoActionPerformed(evt);
            }
        });

        jLabel5.setText("Apellidos:");

        jLabel6.setText("Salario");

        jLabel7.setText("Email");

        CbEmpleadosDpto.setModel(modeloComboDepartamentosEmp);

        jLabel8.setText("Departamento");

        spinnerEmpleadoSalario.setModel(new javax.swing.SpinnerNumberModel(1017, 1017, null, 10));

        javax.swing.GroupLayout PanelDetalleEmpleadosLayout = new javax.swing.GroupLayout(PanelDetalleEmpleados);
        PanelDetalleEmpleados.setLayout(PanelDetalleEmpleadosLayout);
        PanelDetalleEmpleadosLayout.setHorizontalGroup(
            PanelDetalleEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleEmpleadosLayout.createSequentialGroup()
                .addGroup(PanelDetalleEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleEmpleadosLayout.createSequentialGroup()
                        .addGroup(PanelDetalleEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDetalleEmpleadosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelDetalleEmpleadosLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(BtGuardarEmpleado)))
                        .addGap(18, 18, 18)
                        .addComponent(BtNuevoEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(BtBorrarEmpleado))
                    .addGroup(PanelDetalleEmpleadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelDetalleEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(JTexFieldEmpleadoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTexFieldEmpleadoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTexFieldEmpleadoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTexFieldEmpleadoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbEmpleadosDpto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerEmpleadoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PanelDetalleEmpleadosLayout.setVerticalGroup(
            PanelDetalleEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleEmpleadosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTexFieldEmpleadoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTexFieldEmpleadoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTexFieldEmpleadoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerEmpleadoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTexFieldEmpleadoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CbEmpleadosDpto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(PanelDetalleEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtGuardarEmpleado)
                    .addComponent(BtNuevoEmpleado)
                    .addComponent(BtBorrarEmpleado))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout TabEmpleadosLayout = new javax.swing.GroupLayout(TabEmpleados);
        TabEmpleados.setLayout(TabEmpleadosLayout);
        TabEmpleadosLayout.setHorizontalGroup(
            TabEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabEmpleadosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(PanelListadoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelDetalleEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        TabEmpleadosLayout.setVerticalGroup(
            TabEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabEmpleadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TabEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelListadoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelDetalleEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Empleados", TabEmpleados);

        PanelListadoDepartamentos.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado:"));

        jListDpto.setModel(modeloJlistDptos);
        jListDpto.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListDptoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListDpto);

        javax.swing.GroupLayout PanelListadoDepartamentosLayout = new javax.swing.GroupLayout(PanelListadoDepartamentos);
        PanelListadoDepartamentos.setLayout(PanelListadoDepartamentosLayout);
        PanelListadoDepartamentosLayout.setHorizontalGroup(
            PanelListadoDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoDepartamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelListadoDepartamentosLayout.setVerticalGroup(
            PanelListadoDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoDepartamentosLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelDetalleDepartamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle:"));

        jLabel1.setText("ID:");

        JTexFieldDptoID.setEditable(false);
        JTexFieldDptoID.setEnabled(false);
        JTexFieldDptoID.setPreferredSize(new java.awt.Dimension(70, 23));

        jLabel2.setText("Nombre:");

        BtGuardarDpto.setText("GUARDAR");
        BtGuardarDpto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardarDptoActionPerformed(evt);
            }
        });

        BtNuevoDpto.setText("NUEVO");
        BtNuevoDpto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNuevoDptoActionPerformed(evt);
            }
        });

        BtBorrarDpto.setText("BORRAR");
        BtBorrarDpto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBorrarDptoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDetalleDepartamentoLayout = new javax.swing.GroupLayout(PanelDetalleDepartamento);
        PanelDetalleDepartamento.setLayout(PanelDetalleDepartamentoLayout);
        PanelDetalleDepartamentoLayout.setHorizontalGroup(
            PanelDetalleDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleDepartamentoLayout.createSequentialGroup()
                .addGroup(PanelDetalleDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleDepartamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelDetalleDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(JTexFieldDptoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTexFieldDptoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelDetalleDepartamentoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(BtGuardarDpto)
                        .addGap(18, 18, 18)
                        .addComponent(BtNuevoDpto)
                        .addGap(18, 18, 18)
                        .addComponent(BtBorrarDpto)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PanelDetalleDepartamentoLayout.setVerticalGroup(
            PanelDetalleDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleDepartamentoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTexFieldDptoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(JTexFieldDptoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDetalleDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtGuardarDpto)
                    .addComponent(BtNuevoDpto)
                    .addComponent(BtBorrarDpto))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout TabDepartamentosLayout = new javax.swing.GroupLayout(TabDepartamentos);
        TabDepartamentos.setLayout(TabDepartamentosLayout);
        TabDepartamentosLayout.setHorizontalGroup(
            TabDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabDepartamentosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(PanelListadoDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelDetalleDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        TabDepartamentosLayout.setVerticalGroup(
            TabDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabDepartamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabDepartamentosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PanelListadoDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PanelDetalleDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Departamentos", TabDepartamentos);

        PanelListadoFichas.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado:"));

        jListFichas.setModel(modeloJlistFichar);
        jListFichas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListFichasValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListFichas);

        javax.swing.GroupLayout PanelListadoFichasLayout = new javax.swing.GroupLayout(PanelListadoFichas);
        PanelListadoFichas.setLayout(PanelListadoFichasLayout);
        PanelListadoFichasLayout.setHorizontalGroup(
            PanelListadoFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoFichasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelListadoFichasLayout.setVerticalGroup(
            PanelListadoFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoFichasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        PanelDetalleFicha.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles:"));

        jLabel9.setText("ID Ficha:");

        jTextFieldFichaID.setEditable(false);
        jTextFieldFichaID.setEnabled(false);
        jTextFieldFichaID.setMinimumSize(new java.awt.Dimension(40, 22));
        jTextFieldFichaID.setPreferredSize(new java.awt.Dimension(40, 22));

        jLabel10.setText("Nombre Empleado:");

        jTextFieldFichaNombreEmpleado.setMinimumSize(new java.awt.Dimension(130, 22));
        jTextFieldFichaNombreEmpleado.setPreferredSize(new java.awt.Dimension(130, 22));

        jLabel11.setText("Tipo de Fichado");

        jButtonGuardarFicha.setText("GUARDAR");
        jButtonGuardarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarFichaActionPerformed(evt);
            }
        });

        jButtonNuevaFicha.setText("NUEVO");
        jButtonNuevaFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaFichaActionPerformed(evt);
            }
        });

        jButtonBorrarFicha.setText("BORRAR");
        jButtonBorrarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarFichaActionPerformed(evt);
            }
        });

        jTextFieldFichaTipoFichado.setMinimumSize(new java.awt.Dimension(131, 22));
        jTextFieldFichaTipoFichado.setPreferredSize(new java.awt.Dimension(131, 22));

        javax.swing.GroupLayout PanelDetalleFichaLayout = new javax.swing.GroupLayout(PanelDetalleFicha);
        PanelDetalleFicha.setLayout(PanelDetalleFichaLayout);
        PanelDetalleFichaLayout.setHorizontalGroup(
            PanelDetalleFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleFichaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDetalleFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldFichaID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addGroup(PanelDetalleFichaLayout.createSequentialGroup()
                        .addComponent(jButtonGuardarFicha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNuevaFicha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBorrarFicha))
                    .addGroup(PanelDetalleFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldFichaTipoFichado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldFichaNombreEmpleado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        PanelDetalleFichaLayout.setVerticalGroup(
            PanelDetalleFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleFichaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFichaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFichaNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFichaTipoFichado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addGroup(PanelDetalleFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrarFicha)
                    .addComponent(jButtonNuevaFicha)
                    .addComponent(jButtonGuardarFicha))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout TabFichasLayout = new javax.swing.GroupLayout(TabFichas);
        TabFichas.setLayout(TabFichasLayout);
        TabFichasLayout.setHorizontalGroup(
            TabFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabFichasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(PanelListadoFichas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelDetalleFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TabFichasLayout.setVerticalGroup(
            TabFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabFichasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(TabFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelDetalleFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelListadoFichas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fichas", TabFichas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtBorrarDptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBorrarDptoActionPerformed
        // Creamos un objeto Departamento
        Departamento dep = new Departamento();
        
        // Asignamos los valores de la interfaz
        // Comprobamos que el ID existe
        if (!JTexFieldDptoID.getText().isBlank()) {
            dep.setIdDepartamento(Integer.parseInt(JTexFieldDptoID.getText()));
        }        
        // Usamos el método para borrar el departamento
        borrarDepartamento(dep);
    }//GEN-LAST:event_BtBorrarDptoActionPerformed

    private void BtBorrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBorrarEmpleadoActionPerformed
        // Creamos un objeto empleado
        Empleado emp = new Empleado();
        
        if (!JTexFieldEmpleadoID.getText().isBlank()) {
            emp.setIdEmpleado(Integer.parseInt(JTexFieldEmpleadoID.getText()));
        }
        
        borrarEmpleado(emp);
    }//GEN-LAST:event_BtBorrarEmpleadoActionPerformed

    private void jListDptoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListDptoValueChanged
        mostrarDatosDpto(jListDpto.getSelectedIndex());
    }//GEN-LAST:event_jListDptoValueChanged

    private void jListEmpleadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListEmpleadosValueChanged
        mostrarDatosEmpleados(jListEmpleados.getSelectedIndex());
    }//GEN-LAST:event_jListEmpleadosValueChanged

    private void BtNuevoDptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNuevoDptoActionPerformed
        limpiarDetallesDepartamento();
    }//GEN-LAST:event_BtNuevoDptoActionPerformed

    private void BtGuardarDptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardarDptoActionPerformed
        // Creamos un objeto departamento
        Departamento dep = new Departamento();
        
        // Asignamos los valores de la interfaz
        // Comprobamos que el ID existe
        if (!JTexFieldDptoID.getText().isBlank()) {
            dep.setIdDepartamento(Integer.parseInt(JTexFieldDptoID.getText()));
        }
        
        dep.setNombre(JTexFieldDptoNombre.getText());
        
        // Usamos el método para guardar el departamento
        guardarDepartamento(dep);
    }//GEN-LAST:event_BtGuardarDptoActionPerformed

    private void BtNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNuevoEmpleadoActionPerformed
        limpiarDetallesEmpleados();
    }//GEN-LAST:event_BtNuevoEmpleadoActionPerformed

    private void BtGuardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardarEmpleadoActionPerformed
        // Creamos un objeto empleado
        Empleado emp = new Empleado();
        
        if (!JTexFieldEmpleadoID.getText().isBlank()) {
            emp.setIdEmpleado(Integer.parseInt(JTexFieldEmpleadoID.getText()));
        }
        
        // Asignamos los valores al empleado
        emp.setNombre(JTexFieldEmpleadoNombre.getText());
        emp.setApellido(JTexFieldEmpleadoApellidos.getText());
        emp.setSalario(Float.parseFloat(spinnerEmpleadoSalario.getValue().toString()));
        emp.setEmail(JTexFieldEmpleadoEmail.getText());
        emp.setDpt(listaDepartamentos.getDepartamentoBis(CbEmpleadosDpto.getSelectedIndex()));
        
        guardarEmpleado(emp);
    }//GEN-LAST:event_BtGuardarEmpleadoActionPerformed

    private void jListFichasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListFichasValueChanged
        mostrarDatosFichas(jListFichas.getSelectedIndex());
    }//GEN-LAST:event_jListFichasValueChanged

    private void jButtonNuevaFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaFichaActionPerformed
        limpiarDetallesFichas();
    }//GEN-LAST:event_jButtonNuevaFichaActionPerformed

    private void jButtonBorrarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarFichaActionPerformed
        // Creamos un objeto Ficha
        Ficha ficha = new Ficha();
        
        // Asignamos los valores de la interfaz
        // Comprobamos que el ID existe
        if (!jTextFieldFichaID.getText().isBlank()) {
            ficha.setIdFicha(Integer.parseInt(jTextFieldFichaID.getText()));
        }
        
        // Usamos el método para borrar la ficha
        borrarFicha(ficha);
    }//GEN-LAST:event_jButtonBorrarFichaActionPerformed

    private void jButtonGuardarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarFichaActionPerformed
        // Creamos un objeto empleado
        Ficha ficha = new Ficha();
        
        if (!jTextFieldFichaID.getText().isBlank()) {
            ficha.setIdFicha(Integer.parseInt(jTextFieldFichaID.getText()));
        }
        
        // Comprobamos el tipo de ficha y asignamos valores
        if (jTextFieldFichaTipoFichado.getText().equalsIgnoreCase("entrada")) {
            ficha.setEntrada(true);
            ficha.setSalida(false);
        } else if (jTextFieldFichaTipoFichado.getText().equalsIgnoreCase("salida")) {
            ficha.setEntrada(false);
            ficha.setSalida(true);
        }
        
        // Obtenemos el id de la ficha mediante el campo del nombre 
        try {
            ficha.getEmpleado().setIdEmpleado(conexion.buscarEmpleado(jTextFieldFichaNombreEmpleado.getText()).getIdEmpleado());
        } catch (Exception ex) {
            System.err.println("Error: " + ex.getMessage());
        }
        
        guardarFicha(ficha);
    }//GEN-LAST:event_jButtonGuardarFichaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpresaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpresaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpresaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpresaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpresaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBorrarDpto;
    private javax.swing.JButton BtBorrarEmpleado;
    private javax.swing.JButton BtGuardarDpto;
    private javax.swing.JButton BtGuardarEmpleado;
    private javax.swing.JButton BtNuevoDpto;
    private javax.swing.JButton BtNuevoEmpleado;
    private javax.swing.JComboBox<String> CbEmpleadosDpto;
    private javax.swing.JTextField JTexFieldDptoID;
    private javax.swing.JTextField JTexFieldDptoNombre;
    private javax.swing.JTextField JTexFieldEmpleadoApellidos;
    private javax.swing.JTextField JTexFieldEmpleadoEmail;
    private javax.swing.JTextField JTexFieldEmpleadoID;
    private javax.swing.JTextField JTexFieldEmpleadoNombre;
    private javax.swing.JPanel PanelDetalleDepartamento;
    private javax.swing.JPanel PanelDetalleEmpleados;
    private javax.swing.JPanel PanelDetalleFicha;
    private javax.swing.JPanel PanelListadoDepartamentos;
    private javax.swing.JPanel PanelListadoEmpleados;
    private javax.swing.JPanel PanelListadoFichas;
    private javax.swing.JPanel TabDepartamentos;
    private javax.swing.JPanel TabEmpleados;
    private javax.swing.JPanel TabFichas;
    private javax.swing.JButton jButtonBorrarFicha;
    private javax.swing.JButton jButtonGuardarFicha;
    private javax.swing.JButton jButtonNuevaFicha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListDpto;
    private javax.swing.JList<String> jListEmpleados;
    private javax.swing.JList<String> jListFichas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldFichaID;
    private javax.swing.JTextField jTextFieldFichaNombreEmpleado;
    private javax.swing.JTextField jTextFieldFichaTipoFichado;
    private javax.swing.JSpinner spinnerEmpleadoSalario;
    // End of variables declaration//GEN-END:variables

    
    // --------------- MÉTODOS DEPARTAMENTO ---------------------
    
    
    /**
     * Método para cargar los Departamentos de la BD en el jList de
     * Departamentos
     */
    private void cargarDepartamentos() {
        // Limpiar el listado 
        modeloJlistDptos.clear();
        // Limpiamos el combobox de detalles de los empleados
        modeloComboDepartamentosEmp.removeAllElements();
        
        
        // Actualizar el listado
        listaDepartamentos = conexion.listarDepartamentos();
        
        // Debemos recoger los datos de listaDepartamentos y cargarlas en su jList
        for (Departamento d : listaDepartamentos.getListaDepartamentos()) {
            modeloJlistDptos.addElement(d.getNombre());
            modeloComboDepartamentosEmp.addElement(d.getNombre());
        }
    }
    
    /**
     * Método para cargar los datos del Departamento seleccionado en Detalles
     * @param i - Índice del departamento seleccionado
     */
    private void mostrarDatosDpto(int i) {
        if ( i >= 0) {
            Departamento dep = listaDepartamentos.getDepartamentoBis(i);
            JTexFieldDptoID.setText(String.valueOf(dep.getIdDepartamento()));
            JTexFieldDptoNombre.setText(String.valueOf(dep.getNombre()));
            jListDpto.setSelectedIndex(i);
        }
        
    }
    
    /**
     * Borra el contenido de los campos de Detalles del Departamento
     */
    private void limpiarDetallesDepartamento() {
        
        JTexFieldDptoID.setText("");
        JTexFieldDptoNombre.setText("");
        
    }
    
    /**
     * Método para guardar un departamento nuevo en la BD o actualizar uno 
     * que ya exista en ella
     * @param dep Departamento - Departamento a guardar
     */
    private void guardarDepartamento( Departamento dep ){
        
        if ( dep.getIdDepartamento() == -1 ) {
            // No está insertado, lo insertamos
            conexion.insertarDepartamento(dep);
            // Mostramos el último departamento insertado
            cargarDepartamentos();
            jListDpto.setSelectedIndex(listaDepartamentos.size() - 1);
            
        } else {
            // Si ya tiene un ID asignado, actualizar
            conexion.modificarDepartamento(dep, dep);
            
            // Guardamos posicion actual del JList
            int posSel = jListDpto.getSelectedIndex();
            
            // Actualizamos el listado de dptos
            cargarDepartamentos();
            
            // Establecer posicion anterior del jlist
            jListDpto.setSelectedIndex(posSel);
        
        }
        
    }
    
    /**
     * Método para borrar un departamento de la BD
     * @param dep Departamento - Departamento que queremos borrar
     */
    private void borrarDepartamento( Departamento dep ) {
        
        // Comprobamos que el dpto a borrar es válido
        if (dep.getIdDepartamento() > -1) {
            
            conexion.borrarDepartamento(dep);
            
            // Actualizamos el listado de dptos
            cargarDepartamentos();
            
            // Seleccionamos el último departamento
            jListDpto.setSelectedIndex(listaDepartamentos.size() - 1);
            
        } else {
            System.err.println("El Departamento no existe en la BD");
        }
        
        
    }
    
    
    
    // --------------- MÉTODOS EMPLEADOS ---------------------
    
    
    /**
     * Método para cargar los Empleados de la BD en el jList de Empleados
     */
    private void cargarEmpleados() {
        // Limpiamos el listado
        modeloJlistEmpleados.clear();
        
        // Actualizar el listado
        listaEmpleados = conexion.listarEmpleados();
        
        // Debemos recoger los datos de listaEmpleados y cargarlas en su jList
        for (Empleado e : listaEmpleados.getListaEmpleados()) {
            modeloJlistEmpleados.addElement(e.getNombre());
        }
    }

    

    /**
     * Método para cargar los datos del Empleado seleccionado en Detalles
     * @param indiceSeleccionado - Índice del empleado seleccionado
     */
    private void mostrarDatosEmpleados(int indiceSeleccionado) {
        if ( indiceSeleccionado >= 0) {
            Empleado emp = listaEmpleados.getEmpleadoBis(indiceSeleccionado);
        
            JTexFieldEmpleadoID.setText(String.valueOf(emp.getIdEmpleado()));
            JTexFieldEmpleadoNombre.setText(emp.getNombre());
            JTexFieldEmpleadoApellidos.setText(emp.getApellido());
            spinnerEmpleadoSalario.setValue(emp.getSalario());
            JTexFieldEmpleadoEmail.setText(emp.getEmail());
            CbEmpleadosDpto.setSelectedItem(emp.getDpt().getNombre());
        }
    }
    
    /**
     * Método para limpiar todos los campos de Detalles del Empleado
     */
    private void limpiarDetallesEmpleados(){
        JTexFieldEmpleadoID.setText("");
        JTexFieldEmpleadoNombre.setText("");
        JTexFieldEmpleadoApellidos.setText("");
        spinnerEmpleadoSalario.setValue(1017);
        JTexFieldEmpleadoEmail.setText("");
        CbEmpleadosDpto.setSelectedItem(null);
    }

    /**
     * Método para actualizar o insertar un empleado en la BD, esto se hará en 
     * función de si el Empleado que se recibe como parámetro tiene o no id 
     * respectivamente
     * @param emp Empleado - Empleado que vamos a actualizar o añadir
     */
    private void guardarEmpleado(Empleado emp) {
        if (emp.getIdEmpleado() == -1) {
            // Insertamos el empleado
            conexion.insertarEmpleado(emp);
            // Actualizamos la lista de empleados que se muesta
            cargarEmpleados();
            // Seleccionamos el último empleado
            jListEmpleados.setSelectedIndex(listaEmpleados.size() - 1);
        } else {
            // Actualizamos los ddatos del empleado
            conexion.modificarEmpleado(emp, emp);
            // Obtenemos la posición seleccionada
            int posSel = jListEmpleados.getSelectedIndex();
            // Actualizamos la lista de empleados que se muesta
            cargarEmpleados();
            // Seleccionamos el último empleado
            jListEmpleados.setSelectedIndex(posSel);
        }
    }

    /**
     * Método para borrar un Empleado de la BD
     * @param emp Empleado - Empleado que queremos borrar
     */
    private void borrarEmpleado(Empleado emp) {
        if (emp.getIdEmpleado() > -1) {
            // Borramos el empleado
            conexion.borrarEmpleado(emp);
            // Actualizamos la lista de empleados que se muesta
            cargarEmpleados();
            // Seleccionamos el último empleado
            jListEmpleados.setSelectedIndex(listaEmpleados.size() - 1);
        }
    }

    
    // --------------- MÉTODOS FICHAS ----------------- //
    
    /**
     * Método par cargar las Fichas en el jList de Fichas
     */
    private void cargarFichas() {
        // Limpiamos el listado de Fichas
        modeloJlistFichar.clear();
        
        // Actualizamos la lista de Fichas
        listaFichas = conexion.listarFichas();
        
        String entradaSalida, valorMostrar;
        // Recogemos cada ficha y la introducimos en el listado
        for (Ficha ficha : listaFichas.getListaFichas()) {
            
            // Comprobamos si la ficha ha sido de entrada o salida
            if (ficha.isEntrada()) {
                entradaSalida = "Entrada";
            } else {
                entradaSalida = "Salida";
            }
            
            // Creamos el valor que se mostrará en la lista
            valorMostrar = ficha.getEmpleado().getNombre() + " - " +
                    entradaSalida + " - " + ficha.getFechaFicha();
            
            // Lo añadimos al listado
            modeloJlistFichar.addElement(valorMostrar);
        }
    }
    
    /**
     * Método para mostrar los datos de la fichas en Detalles
     * @param indiceSeleccionado int - Índice seleccionado en el jList de Fichas
     */
    private void mostrarDatosFichas(int indiceSeleccionado) {
        if (indiceSeleccionado >= 0) {
            // Obtenemos la ficha de la posición seleccionada en la lista
            Ficha ficha = listaFichas.getFicha(indiceSeleccionado);
            
            // Establecemos los diferentes datos
            jTextFieldFichaID.setText(String.valueOf(ficha.getIdFicha()));
            jTextFieldFichaNombreEmpleado.setText(ficha.getEmpleado().getNombre());
            
            if (ficha.isEntrada()) {
                jTextFieldFichaTipoFichado.setText("Entrada");
            } else if (ficha.isSalida()) {
                jTextFieldFichaTipoFichado.setText("Salida");
            }
        }
    }
    
    /**
     * Método para limpiar los campos de Detalles de las Fichas
     */
    private void limpiarDetallesFichas(){
        jTextFieldFichaID.setText("");
        jTextFieldFichaNombreEmpleado.setText("");
        jTextFieldFichaTipoFichado.setText("");
    }
    
    /**
     * Método para borrar un Ficha de la BBDD
     * @param ficha Ficha - Ficha que queremos borrar
     */
    private void borrarFicha(Ficha ficha) {
        if (ficha.getIdFicha() > -1) {
            // Borramos la ficha
            conexion.borrarFicha(ficha);
            // Actualizamos la lista de Fichas que se muestra
            cargarFichas();
            // Seleccionamos la última ficha
            jListFichas.setSelectedIndex(listaFichas.size() - 1);
        }
    }
    
    /**
     * Método para actualizar o insertar una ficha en la BD, esto se hará en 
     * función de si la Ficha que se recibe como parámetro tiene o no id 
     * respectivamente
     * @param ficha Empleado - Empleado que vamos a actualizar o añadir
     */
    private void guardarFicha(Ficha ficha) {
        if (ficha.getIdFicha() == -1) {
            // Es una ficha nueva, en función del tipo de fichado se hará
            // una inserción u otra
            
            if (ficha.isEntrada()) {
                conexion.insertarFichaEntrada(ficha);
            } else if (ficha.isSalida()) {
                conexion.insertarFichaSalida(ficha);
            } 
            
            // Actualizamos la lista de fichas que se muesta
            cargarEmpleados();
            // Seleccionamos la última ficha
            jListFichas.setSelectedIndex(listaFichas.size() - 1);
            
        } else {
            // Actualizamos los datos de la ficha
            conexion.modificarFicha(ficha, ficha);
            // Obtenemos la posición seleccionada de la lista
            int posSel = jListFichas.getSelectedIndex();
            // Actualizamos la lista de empleados que se muesta
            cargarFichas();
            // Seleccionamos la último ficha
            jListFichas.setSelectedIndex(posSel);
        }
    }
}