/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import BD.GestionBD;
import javax.swing.JOptionPane;
import modelos.Empleado;

/**
 *
 * @author Mi Pc
 */
public class Login extends javax.swing.JFrame {

    GestionBD conexion;
    /**
     * Creates new form Login
     */
    public Login() {
        // Creamos la conexión a la BD
        conexion = new GestionBD("localhost", "javier",
                "javier", "empresa_v2"
        );
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonN7 = new javax.swing.JButton();
        jButtonN8 = new javax.swing.JButton();
        jButtonN9 = new javax.swing.JButton();
        jButtonN4 = new javax.swing.JButton();
        jButtonN5 = new javax.swing.JButton();
        jButtonN6 = new javax.swing.JButton();
        jButtonN1 = new javax.swing.JButton();
        jButtonN2 = new javax.swing.JButton();
        jButtonN3 = new javax.swing.JButton();
        jButtonN0 = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonValidar = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldLoginCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BIENVENIDO AL APARTADO DE LOGIN");

        jLabel2.setText("INTRODUZCA SU NOMBRE Y SU CÓDIGO PARA INICIAR SESIÓN");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Código:");

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jButtonN7.setText("7");
        jButtonN7.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonN7.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonN7.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButtonN7, gridBagConstraints);

        jButtonN8.setText("8");
        jButtonN8.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonN8.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonN8.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButtonN8, gridBagConstraints);

        jButtonN9.setText("9");
        jButtonN9.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonN9.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonN9.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButtonN9, gridBagConstraints);

        jButtonN4.setText("4");
        jButtonN4.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonN4.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonN4.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButtonN4, gridBagConstraints);

        jButtonN5.setText("5");
        jButtonN5.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonN5.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonN5.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButtonN5, gridBagConstraints);

        jButtonN6.setText("6");
        jButtonN6.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonN6.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonN6.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButtonN6, gridBagConstraints);

        jButtonN1.setText("1");
        jButtonN1.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonN1.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonN1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButtonN1, gridBagConstraints);

        jButtonN2.setText("2");
        jButtonN2.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonN2.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonN2.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButtonN2, gridBagConstraints);

        jButtonN3.setText("3");
        jButtonN3.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonN3.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonN3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jButtonN3, gridBagConstraints);

        jButtonN0.setText("0");
        jButtonN0.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonN0.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonN0.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonN0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel1.add(jButtonN0, gridBagConstraints);

        jButtonBorrar.setText("<-");
        jButtonBorrar.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonBorrar.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonBorrar.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        jPanel1.add(jButtonBorrar, gridBagConstraints);

        jButtonValidar.setText("OK");
        jButtonValidar.setMaximumSize(new java.awt.Dimension(50, 50));
        jButtonValidar.setMinimumSize(new java.awt.Dimension(50, 50));
        jButtonValidar.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel1.add(jButtonValidar, gridBagConstraints);

        jTextFieldNombre.setMinimumSize(new java.awt.Dimension(100, 22));
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(100, 22));

        jTextFieldLoginCodigo.setEditable(false);
        jTextFieldLoginCodigo.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldLoginCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldLoginCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN0ActionPerformed
        // Guardamos el contenido del textfield del codigo
        String valor = jTextFieldLoginCodigo.getText();
        
        // Actualizamos el valor
        jTextFieldLoginCodigo.setText(valor + "0");
        
        // Repetimos el mismo proceso con el resto de botones pero 
        // con diferentes valores
    }//GEN-LAST:event_jButtonN0ActionPerformed

    private void jButtonN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN1ActionPerformed
        String valor = jTextFieldLoginCodigo.getText();
        jTextFieldLoginCodigo.setText(valor + "1");
    }//GEN-LAST:event_jButtonN1ActionPerformed

    private void jButtonN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN2ActionPerformed
        String valor = jTextFieldLoginCodigo.getText();
        jTextFieldLoginCodigo.setText(valor + "2");
    }//GEN-LAST:event_jButtonN2ActionPerformed

    private void jButtonN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN3ActionPerformed
        String valor = jTextFieldLoginCodigo.getText();
        jTextFieldLoginCodigo.setText(valor + "3");
    }//GEN-LAST:event_jButtonN3ActionPerformed

    private void jButtonN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN4ActionPerformed
        String valor = jTextFieldLoginCodigo.getText();
        jTextFieldLoginCodigo.setText(valor + "4");
    }//GEN-LAST:event_jButtonN4ActionPerformed

    private void jButtonN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN5ActionPerformed
        String valor = jTextFieldLoginCodigo.getText();
        jTextFieldLoginCodigo.setText(valor + "5");
    }//GEN-LAST:event_jButtonN5ActionPerformed

    private void jButtonN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN6ActionPerformed
        String valor = jTextFieldLoginCodigo.getText();
        jTextFieldLoginCodigo.setText(valor + "6");
    }//GEN-LAST:event_jButtonN6ActionPerformed

    private void jButtonN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN7ActionPerformed
        String valor = jTextFieldLoginCodigo.getText();
        jTextFieldLoginCodigo.setText(valor + "7");
    }//GEN-LAST:event_jButtonN7ActionPerformed

    private void jButtonN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN8ActionPerformed
        String valor = jTextFieldLoginCodigo.getText();
        jTextFieldLoginCodigo.setText(valor + "8");
    }//GEN-LAST:event_jButtonN8ActionPerformed

    private void jButtonN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonN9ActionPerformed
        String valor = jTextFieldLoginCodigo.getText();
        jTextFieldLoginCodigo.setText(valor + "9");
    }//GEN-LAST:event_jButtonN9ActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // Guardamos el valor del codigo
        String valor = jTextFieldLoginCodigo.getText();
        // Si su longitud es diferente de 0, hacemos una subcadena quitando
        // el último carácter
        if (valor.length() != 0) {
           valor = valor.substring(0, valor.length() - 1);
            jTextFieldLoginCodigo.setText(valor); 
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
        // Guardamos los valores del nombre y el código
        String codigo = jTextFieldLoginCodigo.getText();
        String nombre = jTextFieldNombre.getText();
        
        // Si la longitud es 4 
        if (codigo.length() == 4) {
            // Obtenemos el id del empleado comprobando el código
            int id = conexion.comprobarCodigo(Integer.parseInt(codigo), nombre);
            
            // Si el id es mayor a 1 es un usuario válido
            if ( id >= 1 ){
                // Obtenemos el empleado mediante su id
                Empleado emp = conexion.buscarEmpleado(id);
                
                // Si el id es 1, se habrá logueado el admin
                if (emp.getIdEmpleado() == 1) {
                    EmpresaGUI ventanaGestion = new EmpresaGUI();
                    JOptionPane.showMessageDialog( null, 
                            "Te has logueado como " + emp.getNombre());
                    this.setVisible(false);
                    ventanaGestion.setVisible(true);
                } else {
                    VentanaFichar ventanaFichar = new VentanaFichar(emp, conexion);
                    JOptionPane.showMessageDialog( null, 
                            "Te has logueado como " + emp.getNombre());
                    this.setVisible(false);
                    ventanaFichar.setVisible(true);
                }
            } else {
                System.err.println("El usuario no existe");
            }
        // En caso contrario
        } else {
            // Mensaje de error
            JOptionPane.showMessageDialog( null, "La longitud "
                    + "introducida en el código es " + codigo.length() + ", "
                    + "debe ser 4.");
        }
    }//GEN-LAST:event_jButtonValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonN0;
    private javax.swing.JButton jButtonN1;
    private javax.swing.JButton jButtonN2;
    private javax.swing.JButton jButtonN3;
    private javax.swing.JButton jButtonN4;
    private javax.swing.JButton jButtonN5;
    private javax.swing.JButton jButtonN6;
    private javax.swing.JButton jButtonN7;
    private javax.swing.JButton jButtonN8;
    private javax.swing.JButton jButtonN9;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldLoginCodigo;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
