/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import BD.GestionBD;
import java.sql.Timestamp;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelos.Empleado;

/**
 *
 * @author Mi Pc
 */
public class VentanaFichar extends javax.swing.JFrame {

    private static Empleado empleado;
    private static GestionBD conexion;
    private Timestamp fechaFicha;
    private String[] nombresFotos = {"1.png", "2.png", "3.png", "4.png", 
                                    "5.png", "6.png", "7.png", "8.png",
                                    "9.png", "10.png"};
    
    /**
     * Creates new form VentanaFichar
     */
    public VentanaFichar( Empleado emp, GestionBD conexion ) {
        int numeroAleatorio = (int)(Math.random() * nombresFotos.length - 1);
        this.empleado = emp;
        this.conexion = conexion;
        
        initComponents();
        
        jButtonFotoEmpleado.setIcon(new ImageIcon(getClass().getResource("/img/" + nombresFotos[numeroAleatorio])));
        mostrarBienvenida(this.conexion.obtenerFechaServidor(), empleado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEntrar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jLabelHora = new javax.swing.JLabel();
        jButtonFotoEmpleado = new javax.swing.JButton();
        jLabelEmpleado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonEntrar.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButtonEntrar.setText("Registrar Entrada");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButtonSalir.setText("Registrar Salida");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonCerrarSesion.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButtonCerrarSesion.setText("Cerrar Sesión");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jLabelHora.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabelHora.setText("¡Bienvenido");

        jButtonFotoEmpleado.setBackground(new java.awt.Color(0, 153, 153));
        jButtonFotoEmpleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jButtonFotoEmpleado.setMaximumSize(new java.awt.Dimension(150, 150));
        jButtonFotoEmpleado.setMinimumSize(new java.awt.Dimension(150, 150));
        jButtonFotoEmpleado.setPreferredSize(new java.awt.Dimension(150, 150));

        jLabelEmpleado.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabelEmpleado.setText("-----!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEmpleado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButtonFotoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButtonEntrar)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButtonCerrarSesion)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonFotoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHora)
                    .addComponent(jLabelEmpleado))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEntrar)
                    .addComponent(jButtonSalir))
                .addGap(18, 18, 18)
                .addComponent(jButtonCerrarSesion)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        try {
            fechaFicha = conexion.obtenerFechaServidor();
            conexion.insertarFichaEntrada(empleado, fechaFicha);
            JOptionPane.showMessageDialog( null, 
                    "Se ha registrado tu entrada a la empresa");
        } catch(Exception ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        try {
            fechaFicha = conexion.obtenerFechaServidor();
            conexion.insertarFichaSalida(empleado, fechaFicha);
            JOptionPane.showMessageDialog( null, 
                    "Se ha registrado tu salida de la empresa");
        } catch(Exception ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        JOptionPane.showMessageDialog( null, 
                    "Has cerrado sesión, volverás a la pantalla incial");
        this.setVisible(false);
        Login ventanaLogin = new Login();
        ventanaLogin.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFichar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFichar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFichar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFichar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFichar(empleado, conexion).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonFotoEmpleado;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelEmpleado;
    private javax.swing.JLabel jLabelHora;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para personalizar el mensaja de bienvenida en función de la hora
     * y del empleado logueado
     * @param hora Timestamp - Hora del server que vamos a filtar
     * @param emp Empleado - Empleado al que daremos la bienvenida
     */
    private void mostrarBienvenida(Timestamp hora, Empleado emp) {
        // Obtenemos los digitos de la hora spliteando la hora
        int digitosHora  = Integer.parseInt(hora.toString().split(":")[1].split(":")[0]);
        
        // Filtramos los dígitos, en función de la hora se mostrará
        // un mensaje u otro
        if (digitosHora >= 8 || digitosHora <= 13) {
            jLabelHora.setText("¡Buenos días");
        } else if (digitosHora >= 14 || digitosHora <= 20){
            jLabelHora.setText("¡Buenas tardes");
        } else {
            jLabelHora.setText("¡Buenas noches");
        }
        
        // Establecemos al label el nombre y apellidos del empleado
        jLabelEmpleado.setText(emp.getNombre() + " " + emp.getApellido() + "!");
    }
}
