/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import BD.GestionBD;
import java.sql.Timestamp;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelos.Empleado;
import modelos.Ficha;

/**
 *
 * @author Mi Pc
 */
public class VentanaFichar extends javax.swing.JFrame {

    private static Empleado empleado;
    private static GestionBD conexion;
    private Timestamp fechaFicha;
    private String[] nombresFotos = {"1.png", "2.png", "3.png", "4.png", 
                                    "5.png", "6.png", "7.png", "8.png",
                                    "9.png", "10.png"};
    
    /**
     * Creates new form VentanaFichar
     */
    public VentanaFichar( Empleado emp, GestionBD conexion ) {
        int numeroAleatorio = (int)(Math.random() * nombresFotos.length - 1);
        this.empleado = emp;
        this.conexion = conexion;
        
        initComponents();
        
        jButtonFotoEmpleado.setIcon(new ImageIcon(getClass().getResource("/img/" + nombresFotos[numeroAleatorio])));
        mostrarBienvenida(this.conexion.obtenerFechaServidor(), empleado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonFotoEmpleado = new javax.swing.JButton();
        jPanelFicharBotones = new javax.swing.JPanel();
        jButtonRegistrarEntrada = new javax.swing.JButton();
        jButtonRegistrarSalida = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelHora = new javax.swing.JLabel();
        jLabelEmpleado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jButtonFotoEmpleado.setBackground(new java.awt.Color(0, 153, 153));
        jButtonFotoEmpleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jButtonFotoEmpleado.setMaximumSize(new java.awt.Dimension(150, 150));
        jButtonFotoEmpleado.setMinimumSize(new java.awt.Dimension(150, 150));
        jButtonFotoEmpleado.setPreferredSize(new java.awt.Dimension(150, 150));

        jButtonRegistrarEntrada.setBackground(new java.awt.Color(204, 204, 255));
        jButtonRegistrarEntrada.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButtonRegistrarEntrada.setText("Registrar Entrada");
        jButtonRegistrarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarEntradaActionPerformed(evt);
            }
        });

        jButtonRegistrarSalida.setBackground(new java.awt.Color(204, 204, 255));
        jButtonRegistrarSalida.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButtonRegistrarSalida.setText("Registrar Salida");
        jButtonRegistrarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarSalidaActionPerformed(evt);
            }
        });

        jButtonCerrarSesion.setBackground(new java.awt.Color(204, 0, 0));
        jButtonCerrarSesion.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButtonCerrarSesion.setText("Cerrar Sesión");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFicharBotonesLayout = new javax.swing.GroupLayout(jPanelFicharBotones);
        jPanelFicharBotones.setLayout(jPanelFicharBotonesLayout);
        jPanelFicharBotonesLayout.setHorizontalGroup(
            jPanelFicharBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFicharBotonesLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButtonCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelFicharBotonesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonRegistrarEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegistrarSalida)
                .addGap(32, 32, 32))
        );
        jPanelFicharBotonesLayout.setVerticalGroup(
            jPanelFicharBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFicharBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFicharBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRegistrarEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRegistrarSalida, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jButtonCerrarSesion)
                .addGap(39, 39, 39))
        );

        jLabelHora.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHora.setText("Bienvenido,");

        jLabelEmpleado.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabelEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmpleado.setText("-----");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmpleado)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHora)
                    .addComponent(jLabelEmpleado))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButtonFotoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelFicharBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButtonFotoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelFicharBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarEntradaActionPerformed
        try {
            // Si la ficha que obtenemos es nula, quiere decir que no existe
            // registro de la entrada en el día de hoy, insertamos la ficha 
            // de entrada
            if (!comprobarFicha(conexion.obtenerFichaEntrada(empleado))) {
                fechaFicha = conexion.obtenerFechaServidor();
                conexion.insertarFichaEntrada(empleado, fechaFicha);
                JOptionPane.showMessageDialog( null, 
                        "Se ha registrado tu entrada a la empresa");
            } else {
                // Si ya se ha registrado la entrada hoy, mostramos mensaje
                // de error
                JOptionPane.showMessageDialog( null, 
                        empleado.getNombre() + ", ya has registrado tu entrada "
                                + "a la empresa en el día de hoy");
            }
        } catch(Exception ex) {
            System.err.println(ex.getMessage());
        }
        // Repetimos el mismo procedimiento con el botón de registrar salida
    }//GEN-LAST:event_jButtonRegistrarEntradaActionPerformed

    private void jButtonRegistrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarSalidaActionPerformed
        try {
            if (!comprobarFicha(conexion.obtenerFichaSalida(empleado))) {
                fechaFicha = conexion.obtenerFechaServidor();
                conexion.insertarFichaSalida(empleado, fechaFicha);
                JOptionPane.showMessageDialog( null, 
                        "Se ha registrado tu salida de la empresa");
            } else {
                JOptionPane.showMessageDialog( null, 
                        empleado.getNombre() + ", ya has registrado tu salida "
                                + "de la empresa en el día de hoy");
            }
        } catch(Exception ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonRegistrarSalidaActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        JOptionPane.showMessageDialog( null, 
                    "Has cerrado sesión, volverás a la pantalla incial");
        this.setVisible(false);
        VentanaLogin ventanaLogin = new VentanaLogin();
        ventanaLogin.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFichar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFichar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFichar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFichar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFichar(empleado, conexion).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonFotoEmpleado;
    private javax.swing.JButton jButtonRegistrarEntrada;
    private javax.swing.JButton jButtonRegistrarSalida;
    private javax.swing.JLabel jLabelEmpleado;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFicharBotones;
    // End of variables declaration//GEN-END:variables

    /**
     * Método para personalizar el mensaja de bienvenida en función de la hora
     * y del empleado logueado
     * @param hora Timestamp - Hora del server que vamos a filtar
     * @param emp Empleado - Empleado al que daremos la bienvenida
     */
    private void mostrarBienvenida(Timestamp hora, Empleado emp) {
        // Obtenemos los digitos de la hora spliteando la hora
        int digitosHora  = Integer.parseInt(hora.toString().split(":")[1].split(":")[0]);
        
        // Filtramos los dígitos, en función de la hora se mostrará
        // un mensaje u otro
        if (digitosHora >= 8 || digitosHora <= 13) {
            jLabelHora.setText("¡Buenos días,");
        } else if (digitosHora >= 14 || digitosHora <= 20){
            jLabelHora.setText("¡Buenas tardes,");
        } else {
            jLabelHora.setText("¡Buenas noches,");
        }
        
        // Establecemos al label el nombre y apellidos del empleado
        jLabelEmpleado.setText(emp.getNombre() + " " + emp.getApellido() + "!");
    }
    
    /**
     * Método para comprobar si la Ficha obtenida es válida o no, si cualquier
     * campo es nulo la Ficha no será válida, en este caso se comprobará 
     * solamente el de la fecha ya que solo es necesario que un campo sea nulo.
     * Si la ficha es nula, quiere decir que un Empleado en concreto no 
     * ha insertado una Ficha de entrada o de salida todavía en la BBDD, si la
     * ficha es válida, quiere decir que ese Empleado ya se ha registrado la 
     * entrada o la salida.
     * @param ficha Ficha - Ficha que vamos a comprobar
     * @return boolean - Nos devuelve true si la ficha es válida, en caso
     * contrario nos devuelve false.
     */
    private boolean comprobarFicha(Ficha ficha){
        boolean existe = false;
        
        if (ficha.getFechaFicha() != null) {
            existe = true;
        }
        
        return existe;
    }
}
